name: PHP

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP without code coverage
      uses: shivammathur/setup-php@v1
      with:
        php-version: '8.0'
        coverage: none

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v2
      id: cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install PHP 8 dependencies
      run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest

    - name: Check code style
      run: composer run-script phpcs
